### ISSUE TITLE
Please be compatible with the web platform

### ISSUE THREAD

**Issue by chentianxin** [malikwang/custom_pop_up_menu#1]
Consider replacing Platform.isIOS with TargetPlatform or use a third-party plug-in compatible with the web platform to determine the platform

**Comment by malikwang** [comment]
Sry for my late reply, u can fork to solve this.

**Comment by malikwang** [comment]
> Consider replacing Platform.isIOS with TargetPlatform or use a third-party plug-in compatible with the web platform to determine the platform

Sry for my late reply, you can fork to slove this.

**Comment by malikwang** [comment]
@chentianxin 1.1.2 is compatible with the web platform #5

**Comment by chentianxin** [comment]
> @chentianxin 1.1.2 is compatible with the web platform #5

thanks
