### ISSUE TITLE
Duplicate Menus 

### ISSUE THREAD

**Issue by mast3rmindx** [malikwang/custom_pop_up_menu#11]
![00EA3029-E2FE-446B-B894-C8F1FC4405C2](https://user-images.githubusercontent.com/5974297/132941526-61105740-14d0-4ea2-888f-ff87d63cd5de.png) 

I am using the example menu similar to wechat any idea what would cause this behavior?

**Comment by malikwang** [comment]
> ![00EA3029-E2FE-446B-B894-C8F1FC4405C2](https://user-images.githubusercontent.com/5974297/132941526-61105740-14d0-4ea2-888f-ff87d63cd5de.png)
> 
> I am using the example menu similar to wechat any idea what would cause this behavior?

solved?

**Comment by xxzj990** [comment]
> ![00EA3029-E2FE-446B-B894-C8F1FC4405C2](https://user-images.githubusercontent.com/5974297/132941526-61105740-14d0-4ea2-888f-ff87d63cd5de.png)
> 
> I am using the example menu similar to wechat any idea what would cause this behavior?

1.2.1 works fine

**Comment by axiaofang666** [comment]
遇到了同样的问题，绑定controller后就会这样，怎么解决的？

**Comment by malikwang** [comment]
> 遇到了同样的问题，绑定controller后就会这样，怎么解决的？

你试试1.2.2呢？

**Comment by axiaofang666** [comment]
> > 遇到了同样的问题，绑定控制器后会这样，怎么解决的？
> 
> 你聪明1.2.2呢？

使用的就是1.2.2

**Comment by malikwang** [comment]
> > > 遇到了同样的问题，绑定控制器后会这样，怎么解决的？
> > 
> > 
> > 你聪明1.2.2呢？
> 
> 使用的就是1.2.2

我来看一下是啥问题

**Comment by malikwang** [comment]
> > > 遇到了同样的问题，绑定控制器后会这样，怎么解决的？
> > 
> > 
> > 你聪明1.2.2呢？
> 
> 使用的就是1.2.2

怎么复现的  能贴下演示代码吗

**Comment by axiaofang666** [comment]
我是一个列表 同时绑定了一个controller，不知道是不是这个的原因，但是如果每个都绑定不同的controller，实现起来感觉有点麻烦，或者说 有没有办法 不通过controller也能把这个菜单给关闭呢？

**Comment by malikwang** [comment]
> 我是一个列表 同时绑定了一个controller，不知道是不是这个的原因，但是如果每个都绑定不同的controller，实现起来感觉有点麻烦，或者说 有没有办法 不通过controller也能把这个菜单给关闭呢？

我猜测也是这个原因，多个view使用了同一个。你可以封装一个Manager，里面储存一个controller List

**Comment by axiaofang666** [comment]
好的，谢谢你

**Comment by axiaofang666** [comment]
> > 我是一个列表 同时绑定了一个controller，不知道是不是这个的原因，但是如果每个都绑定不同的controller，实现起来感觉有点麻烦，或者说 有没有办法 不通过controller也能把这个菜单给关闭呢？
> 
> 我猜测也是这个原因，多个view使用了同一个。你可以封装一个Manager，里面储存一个controller List

好的，谢谢你

**Comment by iamsandeepsk** [comment]
Same Issue.. Found any solution?

**Comment by mast3rmindx** [comment]
Sorry for the late reply to this thread but I switched to a different package as this is an issue with the package.

**Comment by Junesui** [comment]
I have the same issue, which package do you use?

> Sorry for the late reply to this thread but I switched to a different package as this is an issue with the package.
