### ISSUE TITLE
pressType: PressType.longPress，设置后无法再使用其它手势组件

### ISSUE THREAD

**Issue by axiaofang666** [malikwang/custom_pop_up_menu#14]
pressType: PressType.longPress，设置后无法再使用其它手势组件 比如 InkWell，因为要实现单击和长按 两种效果，请问有什么办法可以解决吗？

**Comment by axiaofang666** [comment]
@malikwang

**Comment by malikwang** [comment]
> pressType: PressType.longPress，设置后无法再使用其它手势组件 比如 InkWell，因为要实现单击和长按 两种效果，请问有什么办法可以解决吗？

插件的实现就是用的InkWell，我把onTap和onLongPress暴露出来？
<img width="648" alt="image" src="https://user-images.githubusercontent.com/26924433/154948533-d7cc313b-0fed-47f2-b33e-37339691ec8e.png">

**Comment by malikwang** [comment]
@axiaofang666 为什么关了？不需要了？

**Comment by axiaofang666** [comment]
> @axiaofang666为什么关了？不需要了？

是的，已经用别的方式解决了，不过还有个问题，我用 horizontalMargin 修改位置，arrow角标位置不会跟着变化

**Comment by malikwang** [comment]
> > @axiaofang666为什么关了？不需要了？
> 
> 是的，已经用别的方式解决了，不过还有个问题，我用 horizontalMargin 修改位置，arrow角标位置不会跟着变化

这个horizontalMargin存在歧义  实际上是距离屏幕边缘的值  这部分可能会在解决 #13 中加上

**Comment by axiaofang666** [comment]
> > > @axiaofang666为什么关了？不需要了？
> > 
> > 
> > 是的，已经用别的方式解决了，不过还有个问题，我用 horizontalMargin 修改位置，arrow角标位置不会跟着变化
> 
> 这个horizontalMargin存在歧义 实际上是距离屏幕边缘的值 这部分可能会在解决 #13 中加上

好的
