### ISSUE TITLE
CustomPopupMenuController hideMenu not working

### ISSUE THREAD

**Issue by furkanolkay** [malikwang/custom_pop_up_menu#15]
I can never close the menu with controller

`  CustomPopupMenuController _controller = CustomPopupMenuController();`

` CustomPopupMenu(
                  child: Icon(
                    Icons.more_horiz,
                    color: Colors.black,
                  ),
                  controller: _controller,
                  arrowColor: Colors.white,
                  menuBuilder: () => TextButton(
                      onPressed: _controller.hideMenu, child: Text('close'),),
                  pressType: PressType.singleClick,)
`

**Comment by furkanolkay** [comment]
The widget I used was stateless. Since I called controller in stateless, I changed my widget to statefull. Problem solved.

**Comment by jiikawa** [comment]
还是不行啊 跳到其他页面回来 可重现这个问题

**Comment by malikwang** [comment]
> 

你可以附上演示代码
