### ISSUE TITLE
Failed assertion: line 88 pos 12: '_route == ModalRoute.of(context)': is not true.

### ISSUE THREAD

**Issue by read0nly** [malikwang/custom_pop_up_menu#17]
the view structure： ReorderableListView--ListItem---CustomPopupMenu.
When I dragging the item view, everything works fine on iOS platform.
But,When I dragging the item view on Android ,I got :
======== Exception caught by widgets library =======================================================
The following assertion was thrown building CustomPopupMenu(state: _CustomPopupMenuState#b4d4c):
'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 88 pos 12: '_route == ModalRoute.of(context)': is not true.

**Comment by malikwang** [comment]
> the view structure： ReorderableListView--ListItem---CustomPopupMenu. When I dragging the item view, everything works fine on iOS platform. But,When I dragging the item view on Android ,I got : ======== Exception caught by widgets library ======================================================= The following assertion was thrown building CustomPopupMenu(state: _CustomPopupMenuState#b4d4c): 'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 88 pos 12: '_route == ModalRoute.of(context)': is not true.


https://stackoverflow.com/questions/67581389/packageflutter-src-widgets-will-pop-scope-dart-failed-assertion-line-135-po
https://stackoverflow.com/questions/64783780/flutter-failed-assertion-line-61-pos-12-route-modalroute-ofcontext
plz try these solutions.
if these cant solve your problem, plz paste the demo.

**Comment by read0nly** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/25766500/161368899-e4564d14-fc4e-41c4-94da-b7d63411fb93.png">
Here is my temporary solution and it works fine.
I speculate that when dragging the item, the system created a copy of the item, which caused the key to be duplicated or other reasons.
My temporary solution is:  The Widget include the CustomPopupMenu to be recreated every build,On Android.

**Comment by malikwang** [comment]
> <img alt="image" width="590" src="https://user-images.githubusercontent.com/25766500/161368899-e4564d14-fc4e-41c4-94da-b7d63411fb93.png">
> 
> Here is my temporary solution and it works fine. I speculate that when dragging the item, the system created a copy of the item, which caused the key to be duplicated or other reasons. My temporary solution is: The Widget include the CustomPopupMenu to be recreated every build,On Android.

maybe you can set the key to the innner SizedBox

**Comment by read0nly** [comment]
“maybe you can set the key to the innner SizedBox”，it's not fine .

**Comment by read0nly** [comment]
It is necessary to create a new CustomPopupMenu on the Android platform.
I noticed that Android and iOS implementations are different, Android's implementation nests a WillpopScope.

**Comment by malikwang** [comment]
> It is necessary to create a new CustomPopupMenu on the Android platform. I noticed that Android and iOS implementations are different, Android's implementation nests a WillpopScope.

yes. In the first version, ios and android are same. But in the version 1.1.0, WillpopScope are removed on ios because of the swipe gesture issue.
