### ISSUE TITLE
多个CustomPopupMenu共存问题

### ISSUE THREAD

**Issue by yangxiaoweihn** [malikwang/custom_pop_up_menu#18]
大佬 多个CustomPopupMenu对象时 只会有一个_controller.hideMenu();生效 ，其他的都失效的

**Comment by malikwang** [comment]
不太可能吧
一般是多个CustomPopupMenu对象  使用多个controller 不能公用
如果有问题你可以粘上问题代码

**Comment by yangxiaoweihn** [comment]
> 不太可能吧 一般是多个CustomPopupMenu对象 使用多个controller 不能公用 如果有问题你可以粘上问题代码

 定位到问题了  如果菜单弹出来后 在进行页面刷新操作 一定会_controller.hideMenu();失效的 
所以menu内部默认创建的controller或者作用于很小的自定义controller都会出现这个问题 
解决方案：
1. controller作用域扩大到页面级别 
2. 最好menu库内部消化一下

**Comment by malikwang** [comment]
> > 不太可能吧 一般是多个CustomPopupMenu对象 使用多个controller 不能公用 如果有问题你可以粘上问题代码
> 
> 定位到问题了 如果菜单弹出来后 在进行页面刷新操作 一定会_controller.hideMenu();失效的 所以menu内部默认创建的controller或者作用于很小的自定义controller都会出现这个问题 解决方案：
> 
> 1. controller作用域扩大到页面级别
> 2. 最好menu库内部消化一下

是不是rebuild新建了一个controller？
如果是库的原因  贴上问题代码  我看能不能优化一下

**Comment by yangxiaoweihn** [comment]
嗯  是rebuild后新建了controller

**Comment by malikwang** [comment]
> 嗯 是rebuild后新建了controller

好的  那可能跟使用有关  我关闭了

**Comment by yangxiaoweihn** [comment]
```dart
class test extends StatefulWidget {
  @override
  _testState createState() => _testState();
}

class _testState extends State<test> {
  @override
  void initState() {
    super.initState();

    Timer(Duration(seconds: 10), () {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          menus(),
          SizedBox(width: 20),
          menus(),
        ],
      ),
    );
  }

  Widget menus() {
    CustomPopupMenuController _controller = CustomPopupMenuController();

    CustomPopupMenu menu = CustomPopupMenu(
      child: const Icon(Icons.ac_unit),
      menuBuilder: () {
        Widget item(String item) {
          return ListTile(
            title: Text('$item'),
            tileColor: Colors.white,
            onTap: () {
              _controller.hideMenu();
            },
          );
        }

        var container = Column(
          mainAxisSize: MainAxisSize.max,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: ['a', 'b', 'c'].map((e) {
            return item(e);
          }).toList(),
        );
        return container;
      },
      pressType: PressType.singleClick,
      showArrow: false,
      controller: _controller,
    );
    return menu;
  }
}
```

init 有个延时rebuild

**Comment by malikwang** [comment]
> ```dart
> class test extends StatefulWidget {
>   @override
>   _testState createState() => _testState();
> }
> 
> class _testState extends State<test> {
>   @override
>   void initState() {
>     super.initState();
> 
>     Timer(Duration(seconds: 10), () {
>       setState(() {});
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         actions: [
>           menus(),
>           SizedBox(width: 20),
>           menus(),
>         ],
>       ),
>     );
>   }
> 
>   Widget menus() {
>     CustomPopupMenuController _controller = CustomPopupMenuController();
> 
>     CustomPopupMenu menu = CustomPopupMenu(
>       child: const Icon(Icons.ac_unit),
>       menuBuilder: () {
>         Widget item(String item) {
>           return ListTile(
>             title: Text('$item'),
>             tileColor: Colors.white,
>             onTap: () {
>               _controller.hideMenu();
>             },
>           );
>         }
> 
>         var container = Column(
>           mainAxisSize: MainAxisSize.max,
>           crossAxisAlignment: CrossAxisAlignment.stretch,
>           children: ['a', 'b', 'c'].map((e) {
>             return item(e);
>           }).toList(),
>         );
>         return container;
>       },
>       pressType: PressType.singleClick,
>       showArrow: false,
>       controller: _controller,
>     );
>     return menu;
>   }
> }
> ```
> 
> init 有个延时rebuild

当时设计就是一个menu绑定一个controller，但是感觉大家普遍使用场景是多个menu😄，设计的时候没有考虑这一点。
看来只有使用的时候写个controllerlist了😅

**Comment by yangxiaoweihn** [comment]
也不是 跟多个其实关系不大 就是rebuild导致controller重建了 我debug了下 在调用notifyListeners()后监听器数量_count == 0了 
所以我觉得库里面的实现上还是可以优化的

**Comment by malikwang** [comment]
> 也不是 跟多个其实关系不大 就是rebuild导致controller重建了 我debug了下 在调用notifyListeners()后监听器数量_count == 0了 所以我觉得库里面的实现上还是可以优化的

你可以fork一下  然后发起个MR
从你的示例来看  其实这种简单的使用场景 显式的声明一个controller进行隐藏有点多余  未来可以使用一个全局的controller manager去隐藏特定的menu

**Comment by yangxiaoweihn** [comment]
👌
 嗯 是这样的

**Comment by wsdqr001** [comment]
同样遇到了这个问题，有好的解决方法吗 @yangxiaoweihn @malikwang

**Comment by dahvlhldle** [comment]
@wsdqr001 
修改一下源码
`          if (widget.pressType == PressType.singleClick && _canResponse) {
            //  _controller?.showMenu();
            _showMenu();
          }`
再申明一个全局的CustomPopupMenuController
