### ISSUE TITLE
flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by Bahrom2101** [malikwang/custom_pop_up_menu#19]
/D:/flutter_windows_3.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/custom_pop_up_menu-1.2.3+1/lib/src/custom_pop_up_menu.dart(195,20): warning G1E0FE241: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null. [D:\FlutterProjects\billz_cashier_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by malikwang** [comment]
use version 1.2.3+2

**Comment by malikwang** [comment]
comment on #21

**Comment by malikwang** [comment]
- Dart SDK > 2.17.0 && Flutter > 3.0.0 use Version 1.2.4
- Dart SDK < 2.17.0 && Flutter < 3.0.0 use Version 1.2.3+1
