### ISSUE TITLE
WidgetsBinding.instance.addPostFrameCallback failed

### ISSUE THREAD

**Issue by quancey** [malikwang/custom_pop_up_menu#21]
Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' Try calling using ?. instead.

**Comment by malikwang** [comment]
> 

you can use  1.2.3+1
the lastest version fix #19

**Comment by LostInDarkMath** [comment]
@quancey You need to upgrade to Flutter 3.0.0

**Comment by malikwang** [comment]
i have retracted version 1.2.3+2 
#19 this issue is warning, not affect compile

**Comment by LostInDarkMath** [comment]
@malikwang A better solution would be to update the constraints in your `pubspec.yaml` file from
```dart
name: custom_pop_up_menu
description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
repository: https://github.com/malikwang/custom_pop_up_menu
homepage: https://github.com/malikwang/custom_pop_up_menu

version: 1.2.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
```
to 
```dart
name: custom_pop_up_menu
description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
repository: https://github.com/malikwang/custom_pop_up_menu
homepage: https://github.com/malikwang/custom_pop_up_menu

version: 1.2.3+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
```

if you ask me.

**Comment by malikwang** [comment]
> @malikwang A better solution would be to update the constraints in your `pubspec.yaml` file from
> 
> ```dart
> name: custom_pop_up_menu
> description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
> repository: https://github.com/malikwang/custom_pop_up_menu
> homepage: https://github.com/malikwang/custom_pop_up_menu
> 
> version: 1.2.3+1
> 
> environment:
>   sdk: ">=2.12.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> ```
> 
> to
> 
> ```dart
> name: custom_pop_up_menu
> description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
> repository: https://github.com/malikwang/custom_pop_up_menu
> homepage: https://github.com/malikwang/custom_pop_up_menu
> 
> version: 1.2.3+1
> 
> environment:
>   sdk: ">=2.17.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> ```
> 
> if you ask me.

thanks for your solution, i would consider it.

**Comment by malikwang** [comment]
> @malikwang A better solution would be to update the constraints in your `pubspec.yaml` file from
> 
> ```dart
> name: custom_pop_up_menu
> description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
> repository: https://github.com/malikwang/custom_pop_up_menu
> homepage: https://github.com/malikwang/custom_pop_up_menu
> 
> version: 1.2.3+1
> 
> environment:
>   sdk: ">=2.12.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> ```
> 
> to
> 
> ```dart
> name: custom_pop_up_menu
> description: Wrap a widget with CustomPopupMenu, Tap or Long Press this widget, a popup menu would display in a suitable position. 
> repository: https://github.com/malikwang/custom_pop_up_menu
> homepage: https://github.com/malikwang/custom_pop_up_menu
> 
> version: 1.2.3+1
> 
> environment:
>   sdk: ">=2.17.0 <3.0.0"
> 
> dependencies:
>   flutter:
>     sdk: flutter
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> ```
> 
> if you ask me.

change sdk minor version can solve #19 and this issue?

**Comment by LostInDarkMath** [comment]
> change sdk minor version can solve https://github.com/malikwang/custom_pop_up_menu/issues/19 and this issue?

Yes. The problem is, that the Dart team changed the type to a non-nullable type in the newer version of the SDK. So if you remove the null-check operator in order to silent the warning you also need to increase the minimum supported Dart SDK version to 2.17.

**Comment by malikwang** [comment]
> > change sdk minor version can solve #19 and this issue?
> 
> Yes. The problem is, that the Dart team changed the type to a non-nullable type in the newer version of the SDK. So if you remove the null-check operator in order to silent the warning you also need to increase the minimum supported Dart SDK version to 2.17.

If implement a new feature,  I have to publish two versions at the same time? For example, Version 1.2.4 for 2.12, Version 1.2.5 for 2.17.

**Comment by LostInDarkMath** [comment]
No. It is no problem to "force" users to upgrade to the Dart SDK 2.17. Flutter 3 is stable now and other packages do this too. 
And those who are not want to upgrade can stick at version 1.2.3.

**Comment by malikwang** [comment]
> No. It is no problem to "force" users to upgrade to the Dart SDK 2.17. Flutter 3 is stable now and other packages do this too. And those who are not want to upgrade can stick at version 1.2.3.

OK, I get it. I will update the sdk version with a new feature. Any way, thanks for your suggestion.

**Comment by LostInDarkMath** [comment]
You're welcome :)

**Comment by minhnguyenandpad** [comment]
> > No. It is no problem to "force" users to upgrade to the Dart SDK 2.17. Flutter 3 is stable now and other packages do this too. And those who are not want to upgrade can stick at version 1.2.3.
> 
> OK, I get it. I will update the sdk version with a new feature. Any way, thanks for your suggestion.

Hi have you update the lib. I don't see the new version. Still having the warning in WidgetsBinding.instance.addPostFrameCallback

**Comment by NinoBass** [comment]
this still persists guys
Any Updates on this?

**Comment by malikwang** [comment]
- Dart SDK > 2.17.0 && Flutter > 3.0.0 use Version 1.2.4
- Dart SDK < 2.17.0 && Flutter < 3.0.0 use Version 1.2.3+1
@NinoBass @quancey @minhnguyenandpad @LostInDarkMath
