### ISSUE TITLE
Bubble arrows cannot move with the point triggered by the target, causing experience obstacles

### ISSUE THREAD

**Issue by deep-fish-pixel** [malikwang/custom_pop_up_menu#30]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/9193379/195222525-70419762-02f0-4eb5-9121-509fb3c2ab4f.png">
The scene is as shown in the above figure. The center arrow in the red box is inaccurate, causing experience problems. I hope the author can support the point where the arrow follows the target. Thank you!

**Comment by deep-fish-pixel** [comment]
I have solved the problem. I found it was caused by other reasons. Thank you

**Comment by malikwang** [comment]
> I have solved the problem. I found it was caused by other reasons. Thank you

😄
