### ISSUE TITLE
更新1.1.1后 No Material widget found. 了

### ISSUE THREAD

**Issue by honjow** [malikwang/custom_pop_up_menu#4]
看了下是因为inkwell? app是CupertinoApp。所以就是不能用了？

**Comment by malikwang** [comment]
> 看了下是因为inkwell? app是CupertinoApp。所以就是不能用了？

不好意思，这个是前段时间为了增加桌面指针手指导致的
暂时解决办法：1. 控件外层包裹个Material，颜色设置为透明  2. 降级为1.1.0
之后我会修复。

**Comment by honjow** [comment]
ok。我包了个Card也暂时解决了

**Comment by malikwang** [comment]
> ok。我包了个Card也暂时解决了

1.1.2已修复  尝试一下是否解决？
