### ISSUE TITLE
 Null check operator used on a null value

### ISSUE THREAD

**Issue by crazecoder** [malikwang/custom_pop_up_menu#7]
```
 Null check operator used on a null value
 State.context(package:flutter/src/widgets/framework.dart:1095)
_CustomPopupMenuState.initState.<anonymous closure>(package:custom_pop_up_menu/src/custom_pop_up_menu.dart:162)
```

**Comment by malikwang** [comment]
@honjow

**Comment by crazecoder** [comment]
```dart
  @override
  void initState() {
    super.initState();
    _controller = widget.controller;
    if (_controller == null) _controller = CustomPopupMenuController();
    _controller?.addListener(_updateView);
    WidgetsBinding.instance?.addPostFrameCallback((call) {
      if (mounted) {
        _childBox = context.findRenderObject() as RenderBox?;
        _parentBox =
            Overlay.of(context)?.context.findRenderObject() as RenderBox?;
      }
    });
  }
```

**Comment by malikwang** [comment]
> ```dart
>   @override
>   void initState() {
>     super.initState();
>     _controller = widget.controller;
>     if (_controller == null) _controller = CustomPopupMenuController();
>     _controller?.addListener(_updateView);
>     WidgetsBinding.instance?.addPostFrameCallback((call) {
>       if (mounted) {
>         _childBox = context.findRenderObject() as RenderBox?;
>         _parentBox =
>             Overlay.of(context)?.context.findRenderObject() as RenderBox?;
>       }
>     });
>   }
> ```

不好意思，这段时间没怎么关注这个库了。
刚刚升级了1.2.1，可以试一下。
再次感谢。
