### ISSUE TITLE
菜单默认展示位置

### ISSUE THREAD

**Issue by ghost** [malikwang/custom_pop_up_menu#9]
个人以为，菜单默认展示在顶部操作起来会更舒服些。

    bool isTop = true;
    if (anchorBottomY + verticalMargin + arrowSize.height + contentSize.height
        < size.height / 2) {
      isTop = false;
    }

**Comment by malikwang** [comment]
> 个人以为，菜单默认展示在顶部操作起来会更舒服些。
> 
> ```
> bool isTop = true;
> if (anchorBottomY + verticalMargin + arrowSize.height + contentSize.height
>     < size.height / 2) {
>   isTop = false;
> }
> ```

你可以搞个PR，加个可选参数

**Comment by malikwang** [comment]
> 个人以为，菜单默认展示在顶部操作起来会更舒服些。
> 
> ```
> bool isTop = true;
> if (anchorBottomY + verticalMargin + arrowSize.height + contentSize.height
>     < size.height / 2) {
>   isTop = false;
> }
> ```

增加了可选参数：position: PreferredPosition.top/bottom
默认为空，表示自动选择位置
升级到1.2.1
